version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ~/PhpstormProjects:/usr/share/nginx/html
    links:
      - node
      - php74
      - php80
      - php81

  node:
    build: ./node
    ports:
      - "9014:8888"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  php74:
    build: ./php74
    ports:
      - "9074:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  php80:
    build: ./php80
    ports:
      - "9080:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  php81:
    build: ./php81
    ports:
      - "9081:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  mariadb:
    build: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=mariaDBsecret
    ports:
      - "9010:3306"
    volumes:
      - ~/PhpstormProjects/docker-dev-phpstorm/data/mariadb:/var/lib/mysql
