version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ~/PhpstormProjects:/usr/share/nginx/html
    links:
      - node
      - php81
      - php82
      - php83

  node:
    build: ./node
    ports:
      - "9020:8888"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  php81:
    build: ./php81
    ports:
      - "9081:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  php82:
    build: ./php82
    ports:
      - "9082:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  php83:
    build: ./php83
    ports:
      - "9083:9000"
    volumes:
      - ~/PhpstormProjects:/var/www/html
    links:
      - mariadb

  mariadb:
    build: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=mariaDBsecret
    ports:
      - "9010:3306"
    volumes:
      - ~/PhpstormProjects/docker-dev-phpstorm/data/mariadb:/var/lib/mysql
